version:                   '3.7'

services:
  app:
    container_name: docker-chanter
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL:  ${EMAIL}
    restart: always
    depends_on:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27006:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      
networks:
  default:
    external:
      name: ${NETWORK}
