version:         '3.7'

services:

  app:
    environment:
      NODE_ENV:  development
    restart:     'no'
    volumes:
    - .:/usr/src/app/
    ports:
    - '3000:3000'

networks:
  default:
    name:        dev
